<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>intentgraph2</AssemblyName>
    <IsGodotToolsProject>true</IsGodotToolsProject>
  </PropertyGroup>
  <Import Project="..\common.props" />

  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>$(Sts2DataDir)\sts2.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Sts2ModsDir)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\intentgraph2\publish" />
  </Target>
</Project>
