<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IntentGraph2.BaseLib</RootNamespace>
    <IsGodotToolsProject>true</IsGodotToolsProject>
  </PropertyGroup>
  <Import Project="..\common.props" />

  <ItemGroup>
    <ProjectReference Include="..\intentgraph2\intentgraph2core.csproj" />
  </ItemGroup>

  <ItemGroup>
	<AssemblyMetadata Include="RitsuLib.ModSettingsMirror.Mod.intentgraph2.DisableSources" Value="baselib,modconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Alchyr.Sts2.BaseLib" Version="3.2.1"/>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Sts2ModsDir)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\intentgraph2\publish" />
  </Target>

</Project>
