<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>IntentGraph2</RootNamespace>
    <Nullable>enable</Nullable>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <BuildMultipleVersion>true</BuildMultipleVersion>
    <VersionSuffix></VersionSuffix>
  </PropertyGroup>
  <Import Project="..\common.props" />
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.14.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="intentgraph2test" />
  </ItemGroup>
  <ItemGroup>
    <Antlr4 Include="intentgraph2\src\Antlr\Rule.g4">
      <Package>IntentGraph2.Antlr</Package>
    </Antlr4>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(Sts2DataDir)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="sts2">
      <HintPath>$(Sts2DataDir)\sts2.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /-I &quot;$(TargetPath)&quot; &quot;$(Sts2ModsDir)\$(TargetName)$(VersionSuffix)$(TargetExt)&quot; /Y&#xD;&#xA;xcopy &quot;$(TargetDir)Antlr4.Runtime.Standard.dll&quot; &quot;$(Sts2ModsDir)\&quot; /Y&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; /-I &quot;$(ProjectDir)\publish\$(TargetName)$(VersionSuffix)$(TargetExt)&quot; /Y&#xD;&#xA;xcopy &quot;$(TargetDir)Antlr4.Runtime.Standard.dll&quot; &quot;$(ProjectDir)\publish\&quot; /Y" />
  </Target>
  <Target Name="DeployGodotFiles">
    <ItemGroup>
      <GodotFilesToDeploy Include="$(ProjectDir)publish\intentgraph2.pck" />
      <GodotFilesToDeploy Include="$(ProjectDir)intentgraph2.json" />
    </ItemGroup>
    <Copy SourceFiles="@(GodotFilesToDeploy)" DestinationFolder="$(Sts2ModsDir)" />
  </Target>
  <Target Name="BuildMultipleVersion" AfterTargets="BeforeBuild" Condition="'$(BuildMultipleVersion)' == 'true'">
    <MSBuild Projects="$(MSBuildProjectFile)" Targets="Build" Properties="DefineConstants=$(DefineConstants);LESS_THAN_0_110_0;VersionSuffix=-lt-0.110.0;BuildMultipleVersion=false" />
  </Target>
</Project>
