<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IntentGraph2.RitsuLib</RootNamespace>
    <IsGodotToolsProject>true</IsGodotToolsProject>
  </PropertyGroup>
  <Import Project="..\common.props" />

  <ItemGroup>
    <ProjectReference Include="..\intentgraph2\intentgraph2core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RitsuLib">
      <HintPath>$(Steamlib)\steamapps\common\Slay the Spire 2\mods\RitsuLib\STS2-RitsuLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetPath)&quot; &quot;$(Steamlib)\steamapps\common\Slay the Spire 2\mods\&quot; /Y&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)\..\intentgraph2\publish\&quot; /Y" />
  </Target>

</Project>
